server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/uniclub09
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
jwt:
  private-key: 35oKkpd4YgTm5Eq17FxL/T9LI7YgbQFWNygAbIioq7I=